 const uid=()=>globalThis.crypto?.randomUUID?.()||'id-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
 const clone=x=>JSON.parse(JSON.stringify(x));
 const blankChapter=(title='Untitled chapter')=>({id:uid(),title,status:'Outlined',summary:'',text:'',note:'',task:'',idea:'',saved:'',planOutline:'',alignment:'left'});
 const blankProject=(title='My manuscript',type='nonfiction')=>({id:uid(),title,type,chapters:[blankChapter('Chapter one')],sources:[],characters:[],trash:[],history:[],genres:initializeGenreChoices()});
 let data,saveTimer,blocked=false,dirty=false,dialogAction=null,blockReason=null;
 const project=()=>data.projects.find(p=>p.id===data.activeProject);
 function saveStatus(message,error=false){const el=root.querySelector('#w-save-status');el.textContent=message;el.classList.toggle('w-error',error);}
 function initialize(){
  try{data=WritingStore.load();}catch(error){blocked=true;blockReason='corrupt';saveStatus('Saved data could not be read: '+(error.cause?.message||error.message)+'. Import a backup to recover.',true);}
  if(!data){freshWorkspace=true;const p=blankProject();data={version:1,projects:[p],activeProject:p.id,preferences:{},trashProjects:[]};}
  data.trashProjects??=[];
  for(const key of ['theme','font','typing','solidGlass','context','contextTab','prose','hintsVisible'])if(key in data.preferences)state[key]=data.preferences[key];state.focus=false;
  if(!data.projects.some(p=>p.id===data.activeProject))data.activeProject=data.projects[0].id;
  activateProject();
  if(!blocked)saveStatus('Ready · edits save locally');
 }
 function activateProject(){const p=project();p.characters??=[];chapters=p.chapters;state.type=p.type;state.genres=initializeGenreChoices(p.genres);state.selected=p.selected&&chapters.some(c=>c.id===p.selected)?p.selected:chapters[0].id;state.view='write';}
 function syncData(){const p=project();p.type=state.type;p.genres={...state.genres};p.selected=state.selected;data.preferences={theme:state.theme,font:state.font,typing:state.typing,solidGlass:state.solidGlass,context:state.context,contextTab:state.contextTab,hintsVisible:state.hintsVisible,palette:WritingPalette.normalize(state.palette),prose:state.prose,personalDictionary:data.preferences.personalDictionary||[],dictionaryTrash:data.preferences.dictionaryTrash||[]};}
 function flushSave(){clearTimeout(saveTimer);if(!dirty)return !blocked;if(blocked){saveStatus('Saving paused. Download a backup or reopen the app.',true);return false;}syncData();try{WritingStore.save(data);dirty=false;queueFolderBackup();saveStatus('Saved locally · '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}));return true;}catch(error){queueFolderBackup();saveStatus('Save failed · download a backup to keep your work',true);return false;}}
 function scheduleSave(){dirty=true;if(blocked){saveStatus('Saving paused · download a backup',true);return;}saveStatus('Saving…');clearTimeout(saveTimer);saveTimer=setTimeout(flushSave,500);}
 function snapshot(c,label='Saved draft'){const p=project();p.history.unshift({id:uid(),chapterId:c.id,at:new Date().toISOString(),title:label,text:c.text,note:c.note,planOutline:c.planOutline||'',alignment:c.alignment||'left',formats:clone(c.formats||[]),lineSpacing:c.lineSpacing||1.7});}
 function toTrash(kind,item,label,chapterId){project().trash.unshift({id:uid(),kind,item:clone(item),label,...(chapterId?{chapterId}:{}),position:kind==='chapter'?chapters.findIndex(c=>c.id===item.id):null,deletedAt:new Date().toISOString()});}
 function field(name,label,value='',multiline=false){return `<label>${escape(label)}${multiline?`<textarea name="${name}" rows="4">${escape(value)}</textarea>`:`<input name="${name}" value="${escape(value)}" ${name==='title'?'required':''} maxlength="${name==='title'?200:20000}">`}</label>`;}
 function showDialog(title,fields,action,button='Save'){dialogAction=action;document.getElementById('w-dialog-title').textContent=title;document.getElementById('w-dialog-fields').innerHTML=fields+'<p id="w-dialog-error" role="alert" hidden></p>';document.getElementById('w-dialog-save').textContent=button;document.getElementById('w-dialog').showModal();}
 function confirmAction(title,message,action,button='Move to Trash'){showDialog(title,`<p>${escape(message)}</p>`,()=>action(),button);}
 const sourceFields=s=>'<section class="w-dialog-section" aria-label="Source details"><h3>Source details</h3>'+field('title','Title',s.title)+field('author','Author / creator',s.author)+field('locator','Page, date, or location',s.locator)+field('url','Source URL (saved as a reference)',s.url)+'</section><section class="w-dialog-section" aria-label="Quoted passage"><h3>Quoted passage</h3>'+field('quotation','Exact quotation',s.quotation,true)+'</section><section class="w-dialog-section" aria-label="Your notes"><h3>Your notes</h3>'+field('notes','Your own notes',s.notes,true)+'</section>';
 function researchView(){return `<div class="w-row"><h2>Research &amp; elements</h2><button id="w-add-source">Add record</button></div><p class="w-secondary">Keep sources, people, places, and ideas here. URLs are references; save excerpts for offline use.</p><div class="w-list">${project().sources.length?project().sources.map(s=>`<section class="w-plancard"><h3>${escape(s.title)}</h3><p>${escape(s.author||'')}</p><p class="w-secondary">${escape(s.locator||'')}${s.url?'<br>'+escape(s.url):''}</p>${s.quotation?`<section class="w-record-section" aria-label="Exact quotation"><h4>Exact quotation</h4><blockquote>${escape(s.quotation).replace(/\n/g,'<br>')}</blockquote></section>`:''}${s.notes?`<section class="w-record-section" aria-label="Your own notes"><h4>Your own notes</h4><p>${escape(s.notes).replace(/\n/g,'<br>')}</p></section>`:''}<div class="w-row w-record-actions"><button data-edit-source="${s.id}">Edit record</button><button data-delete-source="${s.id}">Delete</button></div></section>`).join(''):'<p>No records yet. Add a source or an element you want to keep nearby.</p>'}</div>`;}
 function revisionView(c){const history=project().history.filter(h=>h.chapterId===c.id);return `<div class="w-row"><h2>Revision pass</h2><button id="w-snapshot">Save a version</button></div><section class="w-section" aria-label="Revision checklist"><h3>Review checklist</h3><p class="w-secondary">${escape(c.title)} · private review checklist</p>${['Show a concrete experience before explaining it.','Check the connection to the previous chapter.','Check source locators and quotation accuracy.'].map((t,i)=>`<label class="w-check"><input type="checkbox" data-review="${i}" ${c.review?.[i]?'checked':''}><span>${t}</span></label>`).join('')}</section><section class="w-section" aria-label="Revision task"><h3>Your revision task</h3><textarea id="w-task" aria-label="Revision task" placeholder="What needs attention?">${escape(c.task)}</textarea><button data-delete-field="task">Delete revision task</button></section>${findReplacePanel()}<div id="w-version-comparison"></div><section class="w-section w-saved-versions" aria-label="Saved versions"><h3>Saved versions</h3><p class="w-secondary">Save milestones here. Restoring a version preserves the current draft as another version.</p>${history.map(h=>`<details class="w-plancard"><summary>${escape(h.title)} · ${escape(new Date(h.at).toLocaleString())}</summary><pre class="w-version-text">${escape(h.text)}</pre><p class="w-secondary">${escape(h.note)}</p><button data-compare-version="${h.id}">Compare with current draft</button><button data-restore-version="${h.id}">Restore this version</button><button data-delete-version="${h.id}">Delete version</button></details>`).join('')||'<p>No saved versions for this chapter yet.</p>'}</section>`;}
 function trashView(){return `<h2>Trash</h2><p class="w-secondary">Restore deleted items here. Permanent deletion cannot be undone.</p><div class="w-list">${project().trash.map(t=>`<section class="w-plancard"><strong>${escape(t.label)}</strong><p class="w-secondary">${escape(t.kind)} · ${escape(new Date(t.deletedAt).toLocaleString())}</p><button data-restore-trash="${t.id}">Restore</button><button data-purge-trash="${t.id}">Delete permanently</button></section>`).join('')||'<p>This project’s Trash is empty.</p>'}${data.trashProjects.map(t=>`<section class="w-plancard"><strong>Project: ${escape(t.item.title)}</strong><p class="w-secondary">Deleted ${escape(new Date(t.deletedAt).toLocaleString())}</p><button data-restore-project="${t.id}">Restore project</button><button data-purge-project="${t.id}">Delete permanently</button></section>`).join('')}</div>`;}
 function exportView(){return `<h2>Export your manuscript</h2><p class="w-secondary">Chapter headings and draft text, in the order below. Private notes and research stay in the project backup.</p><section class="w-section" aria-label="Manuscript export"><h3>Manuscript download</h3><label for="w-format">Output format<select id="w-format">${['PDF','Markdown','TXT','DOCX','Reading HTML'].map(x=>`<option value="${x}" ${state.format===x?'selected':''}>${x==='DOCX'?'Word (.docx)':x}</option>`).join('')}</select></label><ol>${chapters.map(x=>`<li>${escape(x.title)} · ${words(x.text)} words</li>`).join('')}</ol><button id="w-download">Download manuscript</button><button id="w-print">Print / save as PDF</button><p id="w-export-status" role="status" class="w-secondary"></p><p class="w-secondary">Word, PDF, and Reading HTML preserve chapter alignment. TXT and Markdown contain plain text. PDF uses a book serif font with page numbers. For characters outside that font, use Print / save as PDF.</p></section><section class="w-section" aria-label="Complete project backup"><h3>Complete project backup</h3><p class="w-secondary">Includes all projects, character profiles, notes, research, Trash, and saved versions. Keep a copy in a folder or on another drive.</p><button id="w-backup-view">Download full backup</button></section>`;}
 function enrichView(){
  root.querySelector('#w-type').innerHTML=projectTypeOptions(state.type);
  root.querySelector('#w-project').innerHTML=data.projects.map(p=>`<option value="${p.id}" ${p.id===data.activeProject?'selected':''}>${escape(p.title)}</option>`).join('');
  if(state.view==='write'){
   const h=main.querySelector('h2');h.innerHTML=`<input id="w-title" aria-label="Chapter title" value="${escape(selected().title)}">`;
   h.insertAdjacentHTML('afterend',`<div class="w-row w-editor-actions"><details class="w-metadata"><summary>Chapter settings</summary><label>Chapter status<select id="w-status">${['Outlined','Drafting','Revising','Complete'].map(x=>`<option ${selected().status===x?'selected':''}>${x}</option>`).join('')}</select></label><label for="w-project-genre">${genreLabel(state.type)}<select id="w-project-genre">${genreOptions(state.type,state.genres[state.type])}</select></label><label>Text size<select id="w-prose">${[16,18,20,22].map(n=>`<option ${state.prose===n?'selected':''}>${n}</option>`).join('')}</select></label><label class="w-secondary">Chapter synopsis<textarea id="w-summary" aria-label="Chapter synopsis" placeholder="A sentence to orient your next session">${escape(selected().summary)}</textarea></label></details><button id="w-delete-chapter">Delete chapter</button><button id="w-toggle-context">${state.context?'Hide':'Show'} chapter tools</button><button id="w-toggle-hints" aria-expanded="${!!state.hintsVisible}" aria-controls="w-context">${state.hintsVisible?'Hide':'Show'} chapter hints</button></div>`);
   const chapterAlignment=['left','right','justify'].includes(selected().alignment)?selected().alignment:'left';
   main.querySelector('.w-editor-actions').insertAdjacentHTML('beforeend',`<label class="w-alignment-control" for="w-alignment">Draft alignment<select id="w-alignment">${['left','right','justify'].map(value=>`<option value="${value}" ${chapterAlignment===value?'selected':''}>${{left:'Left',right:'Right',justify:'Justified'}[value]}</option>`).join('')}</select></label>`);
   main.querySelector('#w-draft').style.textAlign=chapterAlignment;writingControls();
   const typing=main.querySelector('.w-typing-tools'),status=typing.querySelector('#w-typing-status'),actions=typing.querySelector('#w-typing-actions');
   const modeLabel={off:'Off',suggest:'Suggestions',auto:'Autocorrect'}[state.typing];
   const settings=document.createElement('details');settings.className='w-typing-settings';settings.innerHTML='<summary>Typing help · '+modeLabel+'</summary>';
   while(typing.firstChild){const child=typing.firstChild;if(child===status||child===actions){child.remove();}else settings.append(child);}
   typing.append(settings,status,actions);status.hidden=!lastCorrection&&!typingSuggestions.length;
   if(!main.querySelector('#w-outline'))main.querySelector('#w-draft').insertAdjacentHTML('beforebegin',`<details class="w-outline"><summary>Your chapter outline</summary><textarea id="w-outline" aria-label="Chapter outline" placeholder="Plan this chapter here">${escape(selected().planOutline||'')}</textarea><button data-delete-field="planOutline">Delete outline</button></details>`);
   else main.querySelector('#w-outline').insertAdjacentHTML('afterend','<button data-delete-field="planOutline">Delete outline</button>');
  }
  if(state.contextTab==='notes'){
   const note=context.querySelector('#w-note');if(note)note.insertAdjacentHTML('afterend','<button data-delete-field="note">Delete notes</button>');
   // Replace the illustrative source with real project references.
   const research=context.querySelector('#w-context-research');if(research)research.innerHTML=`<h3>Project research</h3><p class="w-secondary">${project().sources.length} saved records</p><button data-view="research">Open research</button>`;
  }
  if(state.contextTab==='ideas'){context.querySelector('#w-idea').value=selected().idea||'';context.querySelector('#w-saved').value=selected().saved||'';context.querySelector('#w-idea').insertAdjacentHTML('afterend','<button data-delete-field="idea">Delete idea</button>');context.querySelector('#w-saved').insertAdjacentHTML('afterend','<button data-delete-field="saved">Delete passage</button>');}
 }
 function backup(){syncData();const text=WritingStore.serialize(data);WritingExport.download(text,'writing-studio-backup-'+new Date().toISOString().slice(0,10)+'.json','application/json');saveStatus('Backup downloaded · keep it somewhere safe');}
 function remapProject(p){const ids=new Map();p.id=uid();for(const c of p.chapters){ids.set(c.id,uid());c.id=ids.get(c.id);}for(const t of p.trash){t.id=uid();if(t.kind==='chapter'){const old=t.item.id;if(!ids.has(old))ids.set(old,uid());t.item.id=ids.get(old);}}for(const t of p.trash){if(t.chapterId)t.chapterId=ids.get(t.chapterId)||t.chapterId;if(t.kind==='version'){t.item.id=uid();t.item.chapterId=ids.get(t.item.chapterId)||t.item.chapterId;}}for(const h of p.history){h.id=uid();h.chapterId=ids.get(h.chapterId)||h.chapterId;}for(const s of p.sources)s.id=uid();for(const c of p.characters||[])c.id=uid();for(const t of p.trash)if(t.kind==='character')t.item.id=uid();p.selected=ids.get(p.selected)||p.chapters[0].id;}
 function restoreItem(id){const p=project(),i=p.trash.findIndex(t=>t.id===id),t=p.trash[i];if(!t)return;if(t.kind==='chapter'){p.chapters.splice(Number.isInteger(t.position)?Math.max(0,Math.min(t.position,p.chapters.length)):p.chapters.length,0,t.item);state.selected=t.item.id;}else if(t.kind==='source')p.sources.push(t.item);else if(t.kind==='character'){p.characters??=[];if(p.characters.length>=1000){saveStatus('Move a character to Trash before restoring another profile.',true);return;}if(p.characters.some(c=>c.id===t.item.id)){saveStatus('This character is already present. The Trash copy has been kept.',true);return;}p.characters.push(t.item);}else if(t.kind==='version')p.history.unshift(t.item);else{let c=chapters.find(c=>c.id===t.chapterId);if(!c){c=blankChapter('Recovered notes');chapters.push(c);}const key={outline:'planOutline',note:'note',idea:'idea',saved:'saved',task:'task'}[t.kind];if(key)c[key]=(c[key]?c[key]+'\n\n':'')+t.item;}p.trash.splice(i,1);render();scheduleSave();}
 document.getElementById('w-form').addEventListener('submit',e=>{e.preventDefault();const form=new FormData(e.target),values=Object.fromEntries(form.entries());Object.keys(values).forEach(k=>values[k]=values[k].trim());try{dialogAction?.(values);document.getElementById('w-dialog').close();render();scheduleSave();}catch(error){saveStatus(error.message,true);const notice=document.getElementById('w-dialog-error');if(notice){notice.hidden=false;notice.textContent=error.message;}}});
 document.getElementById('w-dialog-cancel').addEventListener('click',()=>document.getElementById('w-dialog').close());
 root.addEventListener('click',e=>{
  const b=e.target.closest('button');if(!b)return;
  const c=selected(),p=project();
  if(b.id==='w-add-chapter')showDialog('Add chapter',field('title','Chapter title'),v=>{const c=blankChapter(v.title);chapters.push(c);state.selected=c.id;state.view='write';});
  else if(b.id==='w-delete-chapter')confirmAction('Delete chapter?',`“${c.title}” and its chapter notes will move to Trash.`,()=>{toTrash('chapter',c,c.title);const i=chapters.indexOf(c);chapters.splice(i,1);if(!chapters.length)chapters.push(blankChapter());state.selected=chapters[Math.min(i,chapters.length-1)].id;});
  else if(b.dataset.deleteField){const key=b.dataset.deleteField,kind=key==='planOutline'?'outline':key;if(c[key])confirmAction('Delete '+kind+'?', 'This item will move to Trash.',()=>{toTrash(kind,c[key],c.title+' · '+kind,c.id);c[key]='';if(key==='planOutline')c.addedGuides={};});}
  else if(b.id==='w-new-project')showDialog('New project',field('title','Project title')+`<label>Project type<select name="type" id="w-new-type">${projectTypeOptions('nonfiction')}</select></label><label>Genre / approach<select name="genre" id="w-new-genre">${genreOptions('nonfiction',WritingGenres.defaults.nonfiction)}</select></label><p class="w-secondary" id="w-new-type-note">${escape(projectTypeNote('nonfiction'))}</p>`,v=>{syncData();if(!library[v.type]?.[v.genre])throw new Error('Choose a supported genre.');const p=blankProject(v.title,v.type);p.genres[v.type]=v.genre;data.projects.push(p);data.activeProject=p.id;activateProject();});
  else if(b.id==='w-rename-project')showDialog('Rename project',field('title','Project title',p.title),v=>p.title=v.title);
  else if(b.id==='w-delete-project')confirmAction('Delete project?',`“${p.title}” and all its contents will move to Trash.`,()=>{syncData();data.trashProjects.unshift({id:uid(),kind:'project',label:p.title,item:clone(p),deletedAt:new Date().toISOString()});data.projects=data.projects.filter(x=>x.id!==p.id);if(!data.projects.length)data.projects.push(blankProject());data.activeProject=data.projects[0].id;activateProject();state.view='trash';});
  else if(b.id==='w-backup'||b.id==='w-backup-view')backup();
  else if(b.id==='w-import')root.querySelector('#w-import-file').click();
  else if(b.id==='w-add-source')showDialog('Add research / element',sourceFields({}),v=>p.sources.push({id:uid(),...v}));
  else if(b.dataset.editSource){const s=p.sources.find(s=>s.id===b.dataset.editSource);showDialog('Edit record',sourceFields(s),v=>Object.assign(s,v));}
  else if(b.dataset.deleteSource){const s=p.sources.find(s=>s.id===b.dataset.deleteSource);confirmAction('Delete record?',`“${s.title}” will move to Trash.`,()=>{toTrash('source',s,s.title);p.sources=p.sources.filter(x=>x.id!==s.id);});}
  else if(b.id==='w-snapshot'){snapshot(c);render();}
  else if(b.dataset.restoreVersion){const h=p.history.find(h=>h.id===b.dataset.restoreVersion);confirmAction('Restore version?','The current draft will be saved as a version before restoring.',()=>{snapshot(c,'Before restore');c.text=h.text;c.note=h.note;c.planOutline=h.planOutline;c.alignment=h.alignment||'left';c.formats=clone(h.formats||[]);c.lineSpacing=h.lineSpacing||1.7;editHistory.delete(c.id);},'Restore');}
  else if(b.dataset.deleteVersion){const h=p.history.find(h=>h.id===b.dataset.deleteVersion);toTrash('version',h,h.title,c.id);p.history=p.history.filter(x=>x.id!==h.id);render();}
  else if(b.dataset.restoreTrash)restoreItem(b.dataset.restoreTrash);
  else if(b.dataset.purgeTrash)confirmAction('Delete permanently?','This item cannot be restored afterward. Download a backup first if you want to keep a copy.',()=>p.trash=p.trash.filter(t=>t.id!==b.dataset.purgeTrash),'Delete permanently');
  else if(b.dataset.restoreProject){const i=data.trashProjects.findIndex(t=>t.id===b.dataset.restoreProject),t=data.trashProjects[i];data.projects.push(t.item);data.trashProjects.splice(i,1);data.activeProject=t.item.id;activateProject();render();}
  else if(b.dataset.purgeProject)confirmAction('Delete project permanently?','The project and all its contents will be removed from this workspace.',()=>data.trashProjects=data.trashProjects.filter(t=>t.id!==b.dataset.purgeProject),'Delete permanently');
  else if(b.id==='w-toggle-context'){state.context=!state.context;render();}
  else if(b.id==='w-download'){
   const name=p.title.replace(/[\\/:*?"<>|]/g,'-')||'manuscript',format=state.format;
   if(format==='PDF'){try{WritingExport.download(WritingPDF.pdf(p),name+'.pdf','application/pdf');root.querySelector('#w-export-status').textContent='PDF download started.';}catch(error){const notice=root.querySelector('#w-export-status');notice.textContent=error.message;notice.classList.add('w-error');}}
   else if(format==='DOCX')WritingExport.download(WritingExport.docx(p),name+'.docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document');
   else if(format==='Reading HTML')WritingExport.download(WritingExport.html(p),name+'.html','text/html');
   else if(format==='TXT'||format==='Plain text')WritingExport.download(WritingExport.text(p),name+'.txt','text/plain');
   else WritingExport.download(WritingExport.markdown(p),name+'.md','text/markdown');
  }else if(b.id==='w-print'){const win=window.open('','_blank');if(win){win.document.open();win.document.write(WritingExport.html(p));win.document.close();win.focus();win.print();}else saveStatus('Allow the reading window to print, or download Reading HTML.',true);}
  if(!['w-import','w-backup','w-backup-view','w-print','w-download'].includes(b.id))scheduleSave();
 });
 root.addEventListener('input',e=>{const el=e.target;if(el.id==='w-title'){selected().title=el.value;tree();}if(el.id==='w-summary')selected().summary=el.value;if(el.id==='w-task')selected().task=el.value;if(!['w-search','w-import-file','w-find-text','w-replace-text'].includes(el.id))scheduleSave();});
 root.addEventListener('change',e=>{
  const el=e.target;
  if(el.id==='w-project'){syncData();data.activeProject=el.value;activateProject();render();}
  else if(el.id==='w-alignment'){selected().alignment=el.value;root.querySelector('#w-draft').style.textAlign=el.value;}
  else if(el.id==='w-status'){selected().status=el.value;tree();}
  else if(el.id==='w-prose'){state.prose=Number(el.value);root.style.setProperty('--w-prose',state.prose+'px');fitText();}
  else if(el.id==='w-format'){state.format=el.value;const notice=root.querySelector('#w-export-status');if(notice){notice.textContent='';notice.classList.remove('w-error');}}
  if(!['w-import-file','w-replace-scope','w-match-case','w-whole-word'].includes(el.id))scheduleSave();
 });
 root.querySelector('#w-import-file').addEventListener('change',async e=>{
  const file=e.target.files[0];e.target.value='';if(!file)return;
  if(file.size>20*1024*1024){saveStatus('Import is too large (maximum 20 MB).',true);return;}
  try{const content=await file.text();if(file.name.toLowerCase().endsWith('.json')){
   const imported=WritingStore.parse(content);
   confirmAction('Import project backup?','Projects will be added as separate copies. Your current projects will remain available.',()=>{
    addBackupCopies(imported);
   },'Import backup');
  }else{showDialog('Import text as chapter',field('title','Chapter title',file.name.replace(/\.[^.]+$/,'')),v=>{const c=blankChapter(v.title);c.text=content;chapters.push(c);state.selected=c.id;state.view='write';});}
  }catch(error){saveStatus('Import failed: '+error.message,true);}
 });
 root.addEventListener('keydown',e=>{if(e.target.id==='w-draft'&&(e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z')scheduleSave();});
 window.addEventListener('pagehide',flushSave);
 document.addEventListener('visibilitychange',()=>{if(document.hidden)flushSave();});
 window.addEventListener('beforeunload',e=>{if(dirty&&!flushSave()){e.preventDefault();e.returnValue='';}});
 window.addEventListener('storage',e=>{if(e.key==='writing-desk-v1'){blocked=true;blockReason='concurrent';saveStatus('Another window changed this workspace. Download a backup, then reload.',true);}});
