#!/usr/bin/env python3
"""Build Writing Desk's offline WordNet thesaurus from official 3.0 archives.

Python standard library only. Supply the database archive, a full archive with
*.exc files, and Princeton's downloaded LICENSE. No network calls are made.
Example:
  python3 work/build_thesaurus.py WNdb-3.0.tar.gz \
    --exceptions-archive WordNet-3.0.tar.gz --license LICENSE
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import tarfile

DATABASE_URL = 'https://wordnetcode.princeton.edu/3.0/WNdb-3.0.tar.gz'
FULL_ARCHIVE_URL = 'https://wordnetcode.princeton.edu/3.0/WordNet-3.0.tar.gz'
LICENSE_URL = 'https://wordnetcode.princeton.edu/3.0/LICENSE'
PARTS = [('noun', 'n'), ('verb', 'v'), ('adj', 'a'), ('adv', 'r')]


def member_text(archive, basename):
    matches = [member for member in archive.getmembers()
               if member.isfile() and Path(member.name).name == basename]
    if len(matches) != 1:
        raise ValueError(f'Expected exactly one {basename} in {archive.name}')
    return archive.extractfile(matches[0]).read().decode('utf-8')


def lemma_key(word):
    return re.sub(r'\s+', '_', word.strip().lower())


def clean_word(word):
    return re.sub(r'\((?:a|p|ip)\)$', '', word).replace('_', ' ')


def build(database, exceptions_archive, license_file, output):
    senses, lookup, offsets, exceptions = [], {}, {}, {}
    with tarfile.open(database) as archive:
        for name, pos in PARTS:
            for line in member_text(archive, 'data.' + name).splitlines():
                if not line or not line[0].isdigit():
                    continue
                fields, gloss = line.split('|', 1)
                fields = fields.split()
                words = [clean_word(fields[4 + 2 * index]) for index in range(int(fields[3], 16))]
                # Definitions stay exact; usage examples (quoted after a semicolon)
                # are omitted to keep the local download compact.
                definition = re.split(r';\s*"', gloss.strip(), maxsplit=1)[0].rstrip()
                offsets[(pos, fields[0])] = len(senses)
                senses.append([pos, definition, '|'.join(words)])
            for line in member_text(archive, 'index.' + name).splitlines():
                if not line or line[0].isspace():
                    continue
                fields = line.split()
                count = int(fields[2])
                ids = [offsets[(pos, offset)] for offset in fields[-count:]]
                key = lemma_key(fields[0])
                entry = lookup.setdefault(key, [])
                entry.extend(sense for sense in ids if sense not in entry)
    with tarfile.open(exceptions_archive) as archive:
        for name, pos in PARTS:
            mapping = {}
            for line in member_text(archive, name + '.exc').splitlines():
                parts = line.split()
                if len(parts) > 1:
                    mapping[lemma_key(parts[0])] = [lemma_key(word) for word in parts[1:]]
            exceptions[pos] = mapping
    source = {'database': DATABASE_URL, 'databaseSha256': hashlib.sha256(Path(database).read_bytes()).hexdigest(),
              'exceptions': FULL_ARCHIVE_URL, 'exceptionsSha256': hashlib.sha256(Path(exceptions_archive).read_bytes()).hexdigest(),
              'license': LICENSE_URL, 'licenseSha256': hashlib.sha256(Path(license_file).read_bytes()).hexdigest()}
    payload = {'version': '3.0', 'license': Path(license_file).read_text(encoding='utf-8'), 'source': source, 'senses': senses, 'index': lookup, 'exceptions': exceptions}
    encoded = json.dumps(payload, ensure_ascii=True, separators=(',', ':'))
    # UMD works from a local page, the portable single-file edition, and Node tests.
    javascript = ('// Generated by work/build_thesaurus.py from Princeton WordNet 3.0.\n'
                  '// Official source URLs and SHA-256 checksums are recorded in data.source.\n'
                  '// Definitions and same-synset alternatives only; usage examples omitted.\n'
                  '// License: WordNet-LICENSE.txt. No runtime download or external service.\n'
                  '(function(root){const data=' + encoded.replace('<', '\\u003c') + ';'
                  'if(typeof module==="object"&&module.exports)module.exports=data;'
                  'if(root)root.WritingWordNetData=data;})(typeof globalThis==="object"?globalThis:this);\n')
    output.mkdir(parents=True, exist_ok=True)
    (output / 'wordnet-data.js').write_text(javascript, encoding='utf-8')
    (output / 'WordNet-LICENSE.txt').write_bytes(Path(license_file).read_bytes())
    print(f'Built {len(lookup):,} lemmas and {len(senses):,} senses; {len(javascript.encode()):,} bytes.')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('database', type=Path)
    parser.add_argument('--exceptions-archive', required=True, type=Path)
    parser.add_argument('--license', required=True, type=Path)
    parser.add_argument('--output', type=Path, default=Path(__file__).resolve().parent.parent / 'app' / 'vendor')
    args = parser.parse_args()
    build(args.database, args.exceptions_archive, args.license, args.output)
