 function helpView(){
  return `<h2>Help and getting started</h2><p class="w-secondary">A quick guide to starting, saving, revising, and keeping your work.</p>
   <section class="w-section" aria-label="Local mode"><h3>Local mode — no account needed</h3><p>Writing Studio opens directly on your computer. You do not need ChatGPT, a ChatGPT account, or a Writing Studio account. Writing, autosave, chapter guidance, character profiles, revision, the thesaurus, and manuscript exports work offline.</p><p>Extract the download and open the Mac or Windows launcher. With no launcher or Python, open Writing Studio.html in your browser and download project backups regularly. The launcher adds automatic folder backups. Keep the same browser and app address to return to your saved workspace.</p><p class="w-secondary">The optional DeepSeek assistant needs your own DeepSeek API key and internet access when you choose Generate. It does not require ChatGPT. Opening an external research link also needs internet access.</p></section>
   <section class="w-section" aria-label="Optional first writing session"><h3>Optional first writing session</h3><ol><li>Create or choose a project, then open Studio.</li><li>Give the chapter a working title and start drafting. You can change the title and order later.</li><li>Check the save status in the project bar. Your work saves locally in this browser as you edit.</li><li>Use the Chapter board to move chapters and explore flexible structure prompts.</li></ol><div class="w-row"><button type="button" data-view="write">Open Studio</button><button type="button" data-view="plan">Open Chapter board</button></div></section>
   <section class="w-section" aria-label="Versions and revision"><h3>Versions and revision</h3><p>Open Revise to save a version before a major change, compare wording, or restore an earlier version. Restoring preserves the current draft as another version first.</p><button type="button" data-view="revise">Open Revise</button></section>
   <section class="w-section" aria-label="Backups and recovery"><h3>Backups and recovery</h3><p>Autosave keeps the current workspace in this browser. Folder backups provide another local copy when you use the launcher. You can also download a portable project backup and import a backup as separate project copies.</p><p class="w-secondary">A manuscript export contains chapter text. A full project backup also contains notes, research, character profiles, Trash, and saved versions.</p><button type="button" data-view="backups">Open Folder backups</button><button type="button" data-view="export">Open Export</button></section>
   <section class="w-section" aria-label="Manuscript exports"><h3>Manuscript exports</h3><p>Choose an output format in Export, review the chapter list, then choose Download manuscript. Use Print / save as PDF when you want the browser's print controls.</p><button type="button" data-view="export">Choose an export format</button></section>
   <section class="w-section" aria-label="Keyboard shortcuts"><h3>Keyboard shortcuts</h3><ul><li>Ctrl/Cmd+B: bold selected draft text</li><li>Ctrl/Cmd+I: italic selected draft text</li><li>Ctrl/Cmd+Z: undo a draft edit; Ctrl/Cmd+Shift+Z: redo</li><li>Ctrl/Cmd+S: save now</li><li>Ctrl/Cmd+Shift+F: open Find and replace</li><li>Ctrl/Cmd+Shift+R: open Read manuscript</li></ul><p class="w-secondary">Ctrl means Control on Windows and Linux; Cmd means Command on Mac.</p></section>
   <section class="w-section" aria-label="Optional writing assistant"><h3>Optional writing assistant</h3><p>The assistant needs the Mac or Windows launcher. In Assistant settings, attach a DeepSeek key for the current launcher session, or create a local key file and enable permission for the launcher to read it. The key file is plain text; its path and instructions appear in the settings.</p><p>Review the text preview and your instruction before choosing Generate. Only Generate sends a request to DeepSeek. Generated suggestions stay separate until you choose to save a note, replace selected words, or append them to a chapter.</p><button type="button" data-view="assistant" data-open-assistant-settings="true">Open Assistant settings</button></section>
  `;
 }
 root.addEventListener('click',e=>{
  const button=e.target.closest('button');if(!button)return;
  if(button.id==='w-clear-search'){
   const search=root.querySelector('#w-search');if(search){search.value='';tree();search.focus();}
  }else if(button.dataset.openAssistantSettings){queueMicrotask(()=>{if(state.view==='assistant')root.querySelector('#w-ai-open-settings')?.click();});}else if(button.dataset.view==='backups'){
   queueMicrotask(()=>{if(state.view==='backups')loadFolderFiles();});
  }
 });
